// {{ name }} — generated by theme-render from colors.toml (do not edit)
$bg: {{ background }};
$fg: {{ foreground }};
$accent: {{ accent }};
$urgent: {{ urgent }};
$inactive: {{ border }};
$bg-alt: {{ shell }}; // shell surfaces: bar, launcher, panels
$surface: {{ surface }}; // cards, notifications
$muted: {{ muted }};
$ok: {{ ok }};
$warn: {{ warn }};
$on-accent: {{ on(accent) }};
