# {{ name }} — generated by theme-render from colors.toml (do not edit)

foreground              {{ foreground }}
background              {{ background }}
selection_foreground    {{ foreground }}
selection_background    {{ selection }}

cursor                  {{ cursor }}
cursor_text_color       {{ background }}
url_color               {{ accent }}

active_border_color     {{ accent }}
inactive_border_color   {{ border }}
bell_border_color       {{ yellow }}

active_tab_foreground   {{ on(accent) }}
active_tab_background   {{ accent }}
inactive_tab_foreground {{ foreground }}
inactive_tab_background {{ border }}
tab_bar_background      {{ shell }}

mark1_foreground {{ background }}
mark1_background {{ blue }}
mark2_foreground {{ background }}
mark2_background {{ magenta }}
mark3_foreground {{ background }}
mark3_background {{ cyan }}

# black
color0  {{ color0 }}
color8  {{ color8 }}
# red
color1  {{ color1 }}
color9  {{ color9 }}
# green
color2  {{ color2 }}
color10 {{ color10 }}
# yellow
color3  {{ color3 }}
color11 {{ color11 }}
# blue
color4  {{ color4 }}
color12 {{ color12 }}
# magenta
color5  {{ color5 }}
color13 {{ color13 }}
# cyan
color6  {{ color6 }}
color14 {{ color14 }}
# white
color7  {{ color7 }}
color15 {{ color15 }}
