-- {{ name }} — generated by theme-render from colors.toml (do not edit)
-- Read by lua/rice/init.lua in the Neovim config.
return {
  name = "{{ name }}",
  mode = "{{ mode }}",
  bg = "{{ background }}",
  fg = "{{ foreground }}",
  accent = "{{ accent }}",
  selection = "{{ selection }}",
  red = "{{ red }}",
  green = "{{ green }}",
  yellow = "{{ yellow }}",
  blue = "{{ blue }}",
  purple = "{{ magenta }}",
  cyan = "{{ cyan }}",
  orange = "{{ mix(red, yellow, 0.5) }}",
  gray = "{{ muted }}",
  comment = "{{ mix(muted, foreground, 0.2) }}",
}
