# {{ name }} — generated by theme-render from colors.toml (do not edit)
# Whole config is theme-managed (swaylock has no include directive) — theme-set
# links it to ~/.config/swaylock/config. The background image is passed via
# --image at invocation time.

font=JetBrainsMono Nerd Font
indicator-radius=100
indicator-thickness=10
ignore-empty-password
show-failed-attempts

color={{ background|strip }}
scaling=fill

ring-color={{ accent|strip }}
ring-clear-color={{ foreground|strip }}
ring-ver-color={{ ok|strip }}
ring-wrong-color={{ urgent|strip }}
inside-color={{ background|strip }}
inside-clear-color={{ background|strip }}
inside-ver-color={{ background|strip }}
inside-wrong-color={{ background|strip }}
line-uses-ring
text-color={{ foreground|strip }}
text-clear-color={{ foreground|strip }}
text-ver-color={{ foreground|strip }}
text-wrong-color={{ foreground|strip }}
separator-color=00000000
key-hl-color={{ accent|strip }}
bs-hl-color={{ urgent|strip }}
