# {{ name }} — generated by theme-render from colors.toml (do not edit)

set $bg       {{ background }}
set $fg       {{ foreground }}
set $accent   {{ accent }}
set $urgent   {{ urgent }}
set $inactive {{ border }}

# window borders follow the accent (focused) and the neutral border color
set $border_focused   {{ alpha(accent, 99) }}
set $border_unfocused {{ alpha(border, cc) }}

client.focused          $border_focused $bg $fg $border_focused $border_focused
client.focused_inactive $border_unfocused $bg $fg $border_unfocused $border_unfocused
client.unfocused        $border_unfocused $bg $fg $border_unfocused $border_unfocused
client.urgent           $urgent $bg $fg $urgent $urgent
