# {{ name }} — generated by theme-render from colors.toml (do not edit)
# tmux status bar + pane colors; sourced by tmux.conf, re-sourced by theme-set.

set -g status-style "bg={{ shell }},fg={{ foreground }}"
set -g pane-border-style "fg={{ border }}"
set -g pane-active-border-style "fg={{ accent }}"
set -g message-style "bg={{ accent }},fg={{ on(accent) }},bold"
set -g message-command-style "bg={{ yellow }},fg={{ on(yellow) }},bold"

# left: session badge
set -g status-left "#[fg={{ on(accent) }},bg={{ accent }},bold] 󰆍 #S #[fg={{ accent }},bg={{ shell }},nobold] "

# right: current directory + clock
set -g status-right "#[fg={{ selection }},bg={{ shell }}]#[fg={{ foreground }},bg={{ selection }}]  #{b:pane_current_path} #[fg={{ cyan }},bg={{ selection }}]#[fg={{ on(cyan) }},bg={{ cyan }},bold]  %H:%M #[default]"

# windows
setw -g window-status-format "#[fg={{ muted }},bg={{ shell }}] #I:#W "
setw -g window-status-current-format "#[fg={{ magenta }},bg={{ shell }}]#[fg={{ on(magenta) }},bg={{ magenta }},bold]#I:#W#[fg={{ magenta }},bg={{ shell }},nobold]"
