# {{ name }} — generated by theme-render from colors.toml (do not edit)
# Sourced by ~/.zshrc for autosuggestion + syntax-highlighting colors.
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg={{ muted }}"

typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={{ red }}'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg={{ magenta }}'
ZSH_HIGHLIGHT_STYLES[alias]='fg={{ green }}'
ZSH_HIGHLIGHT_STYLES[builtin]='fg={{ green }}'
ZSH_HIGHLIGHT_STYLES[function]='fg={{ green }}'
ZSH_HIGHLIGHT_STYLES[command]='fg={{ green }}'
ZSH_HIGHLIGHT_STYLES[precommand]='fg={{ green }},underline'
ZSH_HIGHLIGHT_STYLES[arg0]='fg={{ green }}'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={{ muted }}'
ZSH_HIGHLIGHT_STYLES[path]='underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg={{ cyan }}'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={{ yellow }}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={{ yellow }}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg={{ yellow }}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg={{ yellow }}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg={{ yellow }}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg={{ magenta }}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg={{ magenta }}'
ZSH_HIGHLIGHT_STYLES[comment]='fg={{ muted }}'
