# Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc; anything
# that needs console input (password prompts, [y/n]) must go above this block.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ── Oh My Zsh ────────────────────────────────────────────────────────────
# A git clone in ~/.oh-my-zsh wins if present; otherwise the pacman package
# (oh-my-zsh-git) under /usr/share. Its dir is read-only, so cache and the
# completion dump live in ~/.cache.
if [[ -d $HOME/.oh-my-zsh ]]; then
  export ZSH="$HOME/.oh-my-zsh"
else
  export ZSH=/usr/share/oh-my-zsh
fi
export ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/oh-my-zsh"
[[ -d $ZSH_CACHE_DIR/completions ]] || mkdir -p "$ZSH_CACHE_DIR/completions"

# The prompt theme (powerlevel10k) is sourced directly below instead of through
# ZSH_THEME, so it works whether it comes from pacman or a clone.
ZSH_THEME=""
zstyle ':omz:update' mode disabled   # updates come from pacman
plugins=(git)

# Suggest from history first, then completion. The suggestion color comes from
# the active rice theme (see current-theme.zsh below).
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

source $ZSH/oh-my-zsh.sh

# ── Prompt: Powerlevel10k, configured in ~/.p10k.zsh (`p10k configure`) ──
for _p10k in /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme \
             "$HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme"; do
  [[ -r $_p10k ]] && { source "$_p10k"; break }
done
unset _p10k
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# ── Plugins (pacman packages; syntax highlighting goes last) ─────────────
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ── Theme colors for suggestions + syntax highlighting ───────────────────
# ~/.config/zsh/current-theme.zsh is generated by the rice theme engine. Shells
# that are already open pick up a new theme at their next prompt.
_rice_theme="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/current-theme.zsh"
_rice_theme_stamp=""
_rice_theme_reload() {
  [[ -r $_rice_theme ]] || return
  local stamp; stamp="$(zstat +mtime -- "$_rice_theme" 2>/dev/null)" || return
  [[ $stamp == $_rice_theme_stamp ]] && return
  _rice_theme_stamp=$stamp
  source "$_rice_theme"
}
zmodload -F zsh/stat b:zstat 2>/dev/null
autoload -Uz add-zsh-hook
add-zsh-hook precmd _rice_theme_reload
_rice_theme_reload

# ── Personal ─────────────────────────────────────────────────────────────
alias ls="eza -l"

# Disable Ctrl+L clear screen
bindkey -r '^L'

# Golang
export GOPATH=$HOME/go
export PATH="$GOPATH/bin:$PATH"

# Local binaries (Antigravity CLI installer)
export PATH="$HOME/.local/bin:$PATH"

# Angular CLI autocompletion (only where the CLI is installed)
(( $+commands[ng] )) && source <(ng completion script)

# Kiro CLI post block. Keep at the bottom of this file.
[[ -f "${HOME}/.local/share/kiro-cli/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/.local/share/kiro-cli/shell/zshrc.post.zsh"
