-- Bridge between the rice theme engine and Neovim.
--
-- `lua/rice/palette.lua` is generated by theme-render from the active theme's
-- colors.toml (theme-set links it here). This module turns it into One Dark Pro
-- color overrides, and `reload()` re-applies them — theme-set calls it in every
-- running Neovim, so a theme switch recolors open editors live.
local M = {}

local function palette()
  package.loaded["rice.palette"] = nil -- always re-read the file
  local ok, p = pcall(require, "rice.palette")
  return ok and p or nil
end

--- "onedark" for dark themes, "onelight" for light ones
function M.style()
  local p = palette()
  return (p and p.mode == "light") and "onelight" or "onedark"
end

--- onedarkpro color overrides for both variants (nil if there's no palette yet)
function M.colors()
  local p = palette()
  if not p then
    return nil
  end
  local c = {
    bg = p.bg,
    fg = p.fg,
    black = p.bg,
    white = p.fg,
    red = p.red,
    orange = p.orange,
    yellow = p.yellow,
    green = p.green,
    cyan = p.cyan,
    blue = p.blue,
    purple = p.purple,
    gray = p.gray,
    comment = p.comment,
    highlight = p.accent,
    selection = p.selection,
  }
  return { onedark = c, onelight = c }
end

--- One Dark Pro options, shared by the initial setup and reloads
function M.opts()
  return {
    colors = M.colors() or {},
    highlights = {},
    -- the terminal is translucent (kitty background_opacity), so let it show through
    options = { transparency = true, terminal_colors = true },
  }
end

--- re-apply the active theme (called by theme-set in running instances)
function M.reload()
  if not palette() then
    return
  end
  require("onedarkpro").setup(M.opts())
  vim.cmd.colorscheme(M.style())
end

return M
