/* {{ name }} — generated by theme-render from colors.toml (do not edit).
   theme-set links it to both ~/.config/gtk-3.0/gtk.css and ~/.config/gtk-4.0/gtk.css.
   Overrides the named colors Adwaita (GTK3/GTK4) and libadwaita apps are built from. */


/* libadwaita */
@define-color accent_color {{ accent }};
@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ on(accent) }};
@define-color destructive_color {{ urgent }};
@define-color destructive_bg_color {{ urgent }};
@define-color destructive_fg_color {{ on(urgent) }};
@define-color success_color {{ ok }};
@define-color success_bg_color {{ ok }};
@define-color success_fg_color {{ on(ok) }};
@define-color warning_color {{ warn }};
@define-color warning_bg_color {{ warn }};
@define-color warning_fg_color {{ on(warn) }};
@define-color error_color {{ urgent }};
@define-color error_bg_color {{ urgent }};
@define-color error_fg_color {{ on(urgent) }};
@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};
@define-color view_bg_color {{ view }};
@define-color view_fg_color {{ foreground }};
@define-color headerbar_bg_color {{ shell }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ border }};
@define-color headerbar_backdrop_color {{ background }};
@define-color headerbar_shade_color {{ shade }};
@define-color card_bg_color mix({{ background }}, {{ foreground }}, 0.06);
@define-color card_fg_color {{ foreground }};
@define-color card_shade_color {{ shade }};
@define-color dialog_bg_color {{ background }};
@define-color dialog_fg_color {{ foreground }};
@define-color popover_bg_color {{ shell }};
@define-color popover_fg_color {{ foreground }};
@define-color sidebar_bg_color {{ shell }};
@define-color sidebar_fg_color {{ foreground }};
@define-color sidebar_backdrop_color {{ background }};
@define-color sidebar_shade_color {{ shade }};
@define-color shade_color {{ shade }};
@define-color scrollbar_outline_color {{ border }};

/* Adwaita GTK3 / GTK4 theme names */
@define-color theme_bg_color {{ background }};
@define-color theme_fg_color {{ foreground }};
@define-color theme_base_color {{ view }};
@define-color theme_text_color {{ foreground }};
@define-color theme_selected_bg_color {{ accent }};
@define-color theme_selected_fg_color {{ on(accent) }};
@define-color theme_unfocused_bg_color {{ background }};
@define-color theme_unfocused_fg_color {{ foreground }};
@define-color theme_unfocused_base_color {{ view }};
@define-color theme_unfocused_text_color {{ foreground }};
@define-color theme_unfocused_selected_bg_color {{ accent }};
@define-color theme_unfocused_selected_fg_color {{ on(accent) }};
@define-color insensitive_bg_color mix({{ background }}, {{ view }}, 0.5);
@define-color insensitive_fg_color mix({{ foreground }}, {{ background }}, 0.5);
@define-color insensitive_base_color {{ view }};
@define-color borders {{ border }};
@define-color unfocused_borders {{ border }};
