/**
 * {{ name }} — generated by theme-render from colors.toml (do not edit)
 **/

* {
    background:     {{ shell|upper }}FF;
    background-alt: {{ mix(shell, foreground, 0.08)|upper }}FF;
    foreground:     {{ foreground|upper }}FF;
    selected:       {{ accent|upper }}FF;
    active:         {{ ok|upper }}FF;
    urgent:         {{ urgent|upper }}FF;
}
