#!/usr/bin/env bash
# Symlinks every stow package in this repo into $HOME. Always targets $HOME
# explicitly and resolves the repo root from this script's own location, so
# it works regardless of where the repo was cloned to or what directory
# you're standing in when you run it.
#
# Every directory inside configs/ is one stow package that mirrors $HOME
# (configs/kitty/.config/kitty/... -> ~/.config/kitty/...). Packages are
# auto-discovered; empty ones are skipped (git doesn't track empty dirs anyway).
# Ends with a summary of what was linked. Safe to re-run.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIGS="$REPO_ROOT/configs"
source "$REPO_ROOT/scripts/lib.sh"
summary_trap "stow-all.sh"

PACKAGES=()
for dir in "$CONFIGS"/*/; do
  name="$(basename "$dir")"
  if find "$dir" -type f -print -quit | grep -q .; then
    PACKAGES+=("$name")
  fi
done

if [[ ${#PACKAGES[@]} -eq 0 ]]; then
  echo "No non-empty stow packages found."
  exit 0
fi

echo "Stowing: ${PACKAGES[*]}"
out="$(mktemp)"
trap 'rm -f "$out"; _rc=$?; summary_print "$_SUMMARY_TITLE" "$_rc"' EXIT
set +e
stow -v --no-folding -d "$CONFIGS" -t "$HOME" "${PACKAGES[@]}" >"$out" 2>&1
stow_rc=$?
set -e
grep -E '^(WARNING|ERROR|stow:)|conflict|\* ' "$out" || true
if [[ $stow_rc -ne 0 ]]; then
  summary_warn "stow refused to link anything (messages above — usually a file already exists at the target)"
  exit 1
fi
new_links="$(grep -c '^LINK:' "$out" || true)"

# Verify instead of trusting: every file in every package must now be reachable
# through a link in $HOME that points back at it.
total=0; ok=0; bad=()
for pkg in "${PACKAGES[@]}"; do
  base="$CONFIGS/$pkg"
  while IFS= read -r -d '' src; do
    rel="${src#"$base"/}"
    total=$((total + 1))
    dst="$HOME/$rel"
    if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$src")" ]]; then
      ok=$((ok + 1))
    else
      bad+=("$rel")
    fi
  done < <(find "$base" \( -name node_modules -o -name '@girs' -o -name .stow-local-ignore -o -name current-theme.scss -o -name .gitignore \) -prune -o \( -type f -o -type l \) -print0)
done

summary_add "packages" "${#PACKAGES[@]} — ${PACKAGES[*]}"
summary_add "links" "$total config files: $ok linked ($new_links new this run, $((ok - new_links)) already in place)"
if [[ ${#bad[@]} -gt 0 ]]; then
  summary_add "not linked" "${#bad[@]}"
  summary_warn "not linked: ${bad[*]:0:5}$([[ ${#bad[@]} -gt 5 ]] && echo ' …')"
fi

# AGS resolves its imports through ~/.config/ags/node_modules, which are links into
# the system AGS install (generated by `ags init`, so not part of the repo/package).
if [[ -d /usr/share/ags/js ]]; then
  mkdir -p "$HOME/.config/ags/node_modules"
  ln -sfn /usr/share/ags/js "$HOME/.config/ags/node_modules/ags"
  [[ -d /usr/share/ags/js/node_modules/gnim ]] && ln -sfn /usr/share/ags/js/node_modules/gnim "$HOME/.config/ags/node_modules/gnim"
  summary_add "ags support" "node_modules links in place"
else
  summary_add "ags support" "skipped (AGS is not installed yet — run install.sh)"
fi

# tmux plugins live outside the repo; on a fresh machine, fetch them now that
# tmux.conf is linked (skipped when tmux isn't installed or TPM is already there).
if ! command -v tmux >/dev/null; then
  summary_add "tmux plugins" "skipped (tmux is not installed)"
elif [[ -d "$HOME/.config/tmux/plugins/tpm" ]]; then
  summary_add "tmux plugins" "already installed"
elif "$REPO_ROOT/scripts/tmux-plugins.sh"; then
  summary_add "tmux plugins" "installed just now"
else
  summary_add "tmux plugins" "failed"
  summary_warn "tmux plugins failed — re-run scripts/tmux-plugins.sh"
fi

# the sway/kitty/bar configs read the active theme through links that theme-set creates
if [[ -e "$HOME/.config/sway/current-theme.conf" ]]; then
  summary_add "theme" "active (change it with ~/.config/rice/theme-set <name>)"
else
  summary_add "theme" "none applied yet"
  summary_warn "no theme applied yet — run: ~/.config/rice/theme-set one-dark"
fi
