#!/usr/bin/env bash
# Symlinks every stow package in this repo into $HOME. Always targets $HOME
# explicitly and resolves the repo root from this script's own location, so
# it works regardless of where the repo was cloned to or what directory
# you're standing in when you run it.
#
# Every directory inside configs/ is one stow package that mirrors $HOME
# (configs/kitty/.config/kitty/... -> ~/.config/kitty/...). Packages are
# auto-discovered; empty ones are skipped (git doesn't track empty dirs anyway).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIGS="$REPO_ROOT/configs"

PACKAGES=()
for dir in "$CONFIGS"/*/; do
  name="$(basename "$dir")"
  if find "$dir" -type f -print -quit | grep -q .; then
    PACKAGES+=("$name")
  fi
done

if [[ ${#PACKAGES[@]} -eq 0 ]]; then
  echo "No non-empty stow packages found."
  exit 0
fi

echo "Stowing: ${PACKAGES[*]}"
stow -v --no-folding -d "$CONFIGS" -t "$HOME" "${PACKAGES[@]}"

# AGS resolves its imports through ~/.config/ags/node_modules, which are links into
# the system AGS install (generated by `ags init`, so not part of the repo/package).
if [[ -d /usr/share/ags/js ]]; then
  mkdir -p "$HOME/.config/ags/node_modules"
  ln -sfn /usr/share/ags/js "$HOME/.config/ags/node_modules/ags"
  [[ -d /usr/share/ags/js/node_modules/gnim ]] && ln -sfn /usr/share/ags/js/node_modules/gnim "$HOME/.config/ags/node_modules/gnim"
fi

# tmux plugins live outside the repo; on a fresh machine, fetch them now that
# tmux.conf is linked (skipped when tmux isn't installed or TPM is already there).
if command -v tmux >/dev/null && [[ ! -d "$HOME/.config/tmux/plugins/tpm" ]]; then
  "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/tmux-plugins.sh"
fi
